services:
  - type: web
    name: rag-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: gunicorn rag_project.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rag-database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: USE_S3
        value: True
      - key: GROQ_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_STORAGE_BUCKET_NAME
        sync: false
      - key: AWS_S3_REGION_NAME
        value: us-east-1

databases:
  - name: rag-database
    databaseName: rag_db
    user: rag_user
    plan: free